- name: Actualizar e instalar paquetes
      apt:
        update_cache: yes
        name:
          - git
          - curl
        state: present

- name: Crear un usuario y grupo
      user:
        name: devuser
        groups: admin
        append: yes
        shell: /bin/bash
        create_home: yes
        password: "{{ 'DesarrolloSoftware' | password_hash('sha512') }}"
